### PR TITLE
Issue9 execute scalar

### LINKED ISSUE #9: Unable to mock Dapper ExecuteScalarAsync queries
When I try to mock a call to Dapper's ExecuteScalarAsync method (or seemingly any other typed method returning a primitive type), it fails with:

`  System.Data.DataException : Error parsing column 0 (Id=<null>)
`

The code I'm using is as follows:

```
 IDbConnectionFactory connFactory = Substitute.For<IDbConnectionFactory>();
 DbConnection dbConn = Substitute.For<DbConnection>().SetupCommands();
 dbConn.SetupQuery(q => q.Contains("SELECT TOP 1")).Returns(new { Id = 1 });
 connFactory.GetConnection(default).ReturnsForAnyArgs(dbConn);
```

I inject the mock of IDbConnectionFactory into my class under test so that the returned DbConnection is the one I've mocked (which works fine in every other test case). I've tried a few return values (e.g. new [] { 1 }), but these do not work either. 

Code under test is:

```
 using(IDbConnection conn = _connectionFactory.GetConnection(_DbOptions.CurrentValue.ConnectionString))
 {
     if(conn.State != ConnectionState.Open)
         conn.Open();

     QueryBuilder q = conn.QueryBuilder(
         $@" SELECT TOP 1 Id
             FROM Foo
             WHERE Id = {id}
         )      
     ");

     bool exists = await q.ExecuteScalarAsync<bool>();
...
```
I've also tried calling other Dapper methods on the same query (i.e. Query, which returns nothing). The Dapper code works fine on the real database.

### PR DESCRIPTION
**Pull request by jmg48**
Adds support for ExecuteScalar and its overloads

### CODE REVIEW

File: NSubstitute.DbConnection/NSubstitute.DbConnection/DbConnectionWrapper.cs [hunk 1]
```diff
@@ -35,10 +37,14 @@ public override string ConnectionString
 
         public override void Open() => _inner.Open();
 
+        public override async Task OpenAsync(CancellationToken cancellationToken) => _inner.Open();
+
         public DbDataReader ExecuteReader(IDbCommand mockCommand) => GetMatchingQuery(mockCommand).ExecuteReader(mockCommand);
 
         public int ExecuteNonQuery(IDbCommand mockCommand) => GetMatchingQuery(mockCommand).ExecuteNonQuery(mockCommand);
 
+        public object ExecuteScalar(IDbCommand mockCommand) => GetMatchingQuery(mockCommand).ExecuteScalar(mockCommand);
```
Comment (dom380) [inline NSubstitute.DbConnection/NSubstitute.DbConnection/DbConnectionWrapper.cs:46]: Is this used? Or rather what is this (and the other execute methods) on here used for? They're not part of interface/base class

**Review by dom380 — APPROVED** [review]

File: NSubstitute.DbConnection/NSubstitute.DbConnection/DbConnectionWrapper.cs (hunk 1 above)
Comment (jmg48) [reply NSubstitute.DbConnection/NSubstitute.DbConnection/DbConnectionWrapper.cs:46]: Yes, these three methods are used by `DbConnectionMockExtensions.CreateMockCommand()` and they bind in the mock query behaviour for the Query, NonQuery and now Scalar variants of how you execute a query. There are various async overloads but they all just call the same synchronous method
